version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Instalar dependências
      - run:
          name: Install dependencies
          command: yarn
      # Construir o Storybook
      - run:
          name: Build Storybook
          command: yarn build-storybook

      # Implantar no GitHub Pages
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "luizleno15@gmail.com"
            git config --global user.name "luislenosilva15"
            git checkout -b deploy-$CIRCLE_SHA1
            npx gh-pages -d storybook-static --branch deploy-$CIRCLE_SHA1
