version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build Storybook
          command: yarn build-storybook -o docs-page
      - run:
          name: Archive Storybook
          command: |
            mkdir -p storybook-archives/1
            cp -R docs-page/ storybook-archives/1
