version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Instalar dependências
      - run:
          name: Install dependencies
          command: yarn
      # Construir o Storybook
      - run:
          name: Build Storybook
          command: yarn build-storybook

      # Implantar no GitHub Pages
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "luizleno15@gmail.com"
            git config --global user.name "luislenosilva15"
            git fetch origin gh-pages
            git worktree add -B gh-pages-temp origin/gh-pages
            rm -rf gh-pages-temp/*
            cp -R storybook-static/. gh-pages-temp/
            cd gh-pages-temp
            git add .
            git commit -m "Deploying Storybook to GitHub Pages"
            git push origin gh-pages-temp:gh-pages
            cd ..
            git worktree remove gh-pages-temp --force
