version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Instalar dependências
      - run:
          name: Install dependencies
          command: yarn
      # Construir o Storybook
      - run:
          name: Build Storybook
          command: yarn build-storybook

      # Implantar no GitHub Pages
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "luizleno15@gmail.com"
            git config --global user.name "luislenosilva15"
            git clone --branch gh-pages --single-branch git@github.com:luislenosilva15/storybook.git gh-pages-temp
            rm -rf gh-pages-temp/*
            cp -r storybook-static/* gh-pages-temp/
            cd gh-pages-temp
            git add .
            git commit -m "Deploying Storybook to GitHub Pages"
            git push origin gh-pages
            cd ..
