version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Fix permissions
          command: sudo chown -R $USER /usr/local/lib/node_modules

      - run:
          name: Build Storybook
          command: yarn build-storybook -o docs-page

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Fix permissions
          command: sudo chown -R $USER /usr/local/lib/node_modules
          
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "luizleno15@gmail.com"
            git config --global user.name "luislenosilva15"
            sudo npm install -g gh-pages
            if [ "$CIRCLE_BRANCH" != "gh-pages" ]; then
              npx gh-pages --branch=gh-pages --dist=docs-page/ --dest=. --add
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages