version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    resource_class: medium
        
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build Storybook
          command: yarn run build-storybook
      - run:
          name: Archive Storybook
          command: |
            mkdir -p storybook-archives/$CIRCLE_PR_NUMBER
            cp -R storybook/ storybook-archives/$CIRCLE_PR_NUMBER/
