version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.20.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn

      - run:
          name: Build Storybook
          command: yarn build-storybook-docs

      - run:
          name: Deploy to GitHub Pages
          command: |
            # echo "luislenosilva15.github.io/git@github.com:luislenosilva15/storybook.git" > .circleci/output-dir/url.txt
            git config --global user.email "luizleno15@gmail.com"
            git config --global user.name "luislenosilva15"
            git clone --branch=gh-pages git@github.com:luislenosilva15/storybook.git .deploy_git
            cp -r docs-page/. .deploy_git
            cd .deploy_git
            git add .
            git commit -m "Deploy Storybook for $CIRCLE_BRANCH"
            git push origin gh-pages
