name: Deploy Storybook

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build-storybook -o docs-page

      - name: Rename Storybook directory
        run: |
          mv storybook-static storybook/${{ github.sha }}

      - name: Commit and push Storybook
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: storybook/${{ github.sha }}
          force: true
          directory: storybook/${{ github.sha }}
