name: Deploy Storybook

on:
  push:
    - "*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build-storybook -o docs-page

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./docs-page"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
